### ISSUE TITLE
Segmentation fault EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by zhang2014** [SchrodingerZhu/snmalloc-rs#154] opened 2021-07-04 02:52 UTC
``` text
* thread #32, name = 'tokio-runtime-worker', stop reason = EXC_BAD_ACCESS (code=1, address=0x40)
  * frame #0: 0x000000010105353e fuse-query`::rust_alloc(size_t, size_t) [inlined] snmalloc::EncodeFreeObjectReference::read(this=0x0000000000000040, entropy=0x0000000210022150) at freelist.h:122:32 [opt]
    frame #1: 0x000000010105353e fuse-query`::rust_alloc(size_t, size_t) [inlined] snmalloc::FreeObject::read_next(this=0x0000000000000040, entropy=0x0000000210022150) at freelist.h:158 [opt]
    frame #2: 0x000000010105353e fuse-query`::rust_alloc(size_t, size_t) [inlined] snmalloc::FreeListIter::take(this=<unavailable>, entropy=0x0000000210022150) at freelist.h:244 [opt]
```

**Comment by mjp41** [comment] 2021-07-05 08:43
Hi @zhang2014, sorry you have run into a problem. I am confused by the crash as it seems to be attemping to allocate null, but the out of memory check earlier should have caught that.

Could you provide a few more details of what happens? What platform are you running on? Is this at the start of a test or part way through? What compiler and version are you using?  Can you provide steps to reproduce, so I can see what is happening?

Is it possible to run a debug version of snmalloc, and see if that provides a more detailed stack trace.

**Comment by SchrodingerZhu** [comment] 2021-07-16 18:20
@zhang2014 would you mind check whether it is possible to make up a minimal reproducible example?

**Comment by mjp41** [comment] 2023-06-29 11:45
No follow up for almost two years, so closing.

**Closed by mjp41** 2023-06-29 11:45 UTC
Labels: bug
